import { Icon } from "./Icons";
import { CTA, Disclaimer, SectionHeading } from "./Primitives";

export function SavingsReport() {
  return <section className="section savings-section"><div className="container savings-layout">
    <div><SectionHeading kicker="Understand the proposal" title="A savings report built on your energy use—not a generic promise." text="We organize the assumptions that shape a solar proposal so you can see how consumption, estimated production and bill offset relate."/><ul className="check-list">{["Twelve-month usage profile","Property and system assumptions","Estimated production pattern","Bill-offset explanation","Variables that can change","Clear next-step questions"].map(x=><li key={x}><Icon name="check"/>{x}</li>)}</ul><Disclaimer>Actual results depend on energy usage, system design, weather, roof or site conditions, utility rates, export credits, equipment, approvals and customer behaviour.</Disclaimer><CTA href="/free-solar-assessment">Get Your Solar Proposal</CTA></div>
    <div className="report-card" aria-label="Illustration of how a solar savings report explains electricity use and solar production"><div className="report-head"><span><Icon name="chart"/></span><div><p>Proposal insight</p><h3>Energy profile overview</h3></div></div><div className="report-chart"><div className="chart-grid" aria-hidden="true"/><div className="chart-area consumption" aria-hidden="true"/><div className="chart-line solar" aria-hidden="true"/><div className="chart-legend"><span><i className="navy"/>Electricity use</span><span><i className="yellow"/>Solar production</span></div></div><div className="report-bars"><div><span>Usage reviewed</span><b style={{width:"88%"}}/></div><div><span>Site-fit inputs</span><b style={{width:"72%"}}/></div><div><span>Assumptions explained</span><b style={{width:"80%"}}/></div></div><p className="illustration-label">Illustrative report structure — not customer results</p></div>
  </div></section>;
}
