import Image from "next/image";
import { FAQExplorer } from "@/components/FAQExplorer";
import { Icon } from "@/components/Icons";
import { BreadcrumbSchema, Breadcrumbs, CTA } from "@/components/Primitives";
import { solarFaqCategories, solarFaqs } from "@/data/solarFaqs";
import { site } from "@/data/site";

const sourceLinks = [
  { label: "Alberta micro-generation", href: "https://www.alberta.ca/micro-generation" },
  { label: "Alberta Utilities Consumer Advocate", href: "https://ucahelps.alberta.ca/residential/renewable-energy/micro-generation/" },
  { label: "City of Calgary solar permitting", href: "https://www.calgary.ca/development/home-building/solar.html" },
  { label: "Natural Resources Canada solar resources", href: "https://natural-resources.canada.ca/energy-sources/renewable-energy/photovoltaic-potential-solar-resource-maps-canada" },
];

export function SolarFaqPage() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: solarFaqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
  const pageSchema = { "@context": "https://schema.org", "@type": "WebPage", name: "Solar FAQs Alberta", description: "Get clear answers about solar costs, savings, Alberta winters, micro-generation, permits, installation, financing, commercial systems, and farm solar.", url: `${site.url}/faq/` };
  return <>
    <section className="faq-page-hero"><Image src="/media/installations/roof-array-close.webp" alt="Solar panels installed on an Alberta rooftop" fill priority sizes="100vw" /><div className="faq-hero-rays" aria-hidden="true" /><div className="container faq-page-hero-inner"><p className="service-label">Sun Direct Renewable · Alberta</p><h1>Solar Frequently Asked Questions</h1><p>Clear answers about solar costs, savings, Alberta winters, approvals, installation, financing, farms, and system performance.</p><div className="faq-page-hero-actions"><CTA href="/free-solar-assessment">Get Your Solar Assessment</CTA><CTA href="#questions" secondary>Explore the Questions</CTA></div></div></section>
    <BreadcrumbSchema current="Solar Frequently Asked Questions" path="/faq/" /><Breadcrumbs current="Solar Frequently Asked Questions" />
    <section className="section faq-page-intro"><div className="container"><div className="faq-page-heading"><p className="kicker">Answers built around Alberta solar planning</p><h2>Start with the question that matters to your property.</h2><p>These answers explain the practical issues that shape a solar project. Your final system, timing and financial options still need a review of your property, electricity usage and current requirements.</p></div><div className="faq-topic-cards"><a href="#questions"><Icon name="home" /><strong>Homes & rooftops</strong><span>Suitability, sizing and roof planning</span></a><a href="#questions"><Icon name="chart" /><strong>Costs & bills</strong><span>Pricing, savings and electricity charges</span></a><a href="#questions"><Icon name="sun" /><strong>Alberta conditions</strong><span>Winter, snow and weather considerations</span></a><a href="#questions"><Icon name="building" /><strong>Businesses & farms</strong><span>Commercial and agricultural planning</span></a></div></div></section>
    <section className="faq-page-resource-strip"><div className="container"><div><Icon name="shield" /><p><strong>Planning note:</strong> Alberta micro-generation, municipal permitting, retailer credit terms and incentives can change. Confirm the current rules before relying on them for a project decision.</p></div><a href="/solar-incentives-financing">Explore incentives & financing <Icon name="arrow" /></a></div></section>
    <section className="section faq-page-questions" id="questions"><div className="container"><div className="faq-page-heading centered"><p className="kicker">Search or browse</p><h2>Clear, practical solar answers.</h2><p>Choose a topic or search for a question. Each answer is written to help you prepare for a more useful solar assessment.</p></div><FAQExplorer categories={solarFaqCategories} faqs={solarFaqs} /></div></section>
    <section className="faq-mid-cta"><div className="container"><div><p className="kicker">Still deciding?</p><h2>Still Unsure If Solar Fits Your Property?</h2><p>Bring us your electricity usage, property type and the questions that matter most. We’ll help you organize the next practical steps.</p></div><CTA href="/free-solar-assessment">Get Your Solar Assessment</CTA></div></section>
    <section className="section faq-page-links"><div className="container faq-page-links-grid"><div><p className="kicker">Keep exploring</p><h2>Useful next steps for a more complete review.</h2><p>Move from broad questions into the service, savings and property details that shape a real project conversation.</p></div><div className="faq-internal-links"><a href="/residential-solar"><Icon name="home" />Residential solar</a><a href="/commercial-solar"><Icon name="building" />Commercial solar</a><a href="/agricultural-solar"><Icon name="leaf" />Farm & agricultural solar</a><a href="/our-process#savings-report"><Icon name="chart" />Savings analysis</a><a href="/our-process"><Icon name="files" />Our process</a><a href="/service-areas"><Icon name="map" />Service areas</a></div></div></section>
    <section className="section faq-page-sources"><div className="container"><div className="faq-page-heading centered"><p className="kicker">Official resources</p><h2>Where to verify current Alberta requirements.</h2><p>Program and regulatory details should be checked with the responsible authority before a project starts.</p></div><div>{sourceLinks.map((source) => <a key={source.href} href={source.href} target="_blank" rel="noopener noreferrer">{source.label}<Icon name="arrow" /></a>)}</div></div></section>
    <section className="faq-page-final"><div className="faq-page-final-rays" aria-hidden="true" /><div className="container"><div><p className="kicker light">A property-specific answer</p><h2>Get Answers Based on Your Actual Property</h2><p>Share your electricity usage and property details, and we’ll prepare a solar assessment based on your specific needs.</p></div><div className="faq-page-final-actions"><CTA href="/free-solar-assessment">Start My Solar Assessment</CTA><CTA href="/contact" secondary>Contact Sun Direct Renewable</CTA></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
  </>;
}
