import Image from "next/image";
import Link from "next/link";
import { FAQList } from "@/components/FAQ";
import { Icon } from "@/components/Icons";
import { BreadcrumbSchema, Breadcrumbs, CTA } from "@/components/Primitives";
import { solarIncentivesData, solarIncentivesFaqs } from "@/data/solarIncentives";
import { site } from "@/data/site";

const overview = [
  { title: "Calgary property-based financing", text: "A municipal financing path for eligible Calgary properties, repaid through property taxes.", href: "#calgary-residential", icon: "home" },
  { title: "Alberta micro-generation credits", text: "Understand on-site use, exported electricity and retailer billing before a system is designed.", href: "#micro-generation", icon: "power" },
  { title: "Business tax incentives", text: "A starting point for organizations reviewing qualifying clean-technology property with tax advice.", href: "#business-tax", icon: "building" },
  { title: "Solar financing options", text: "Compare ownership and repayment paths around your property, project and lender requirements.", href: "#ways-to-pay", icon: "chart" },
] as const;

const paymentOptions = [
  { title: "Cash purchase", text: "Full ownership with no financing interest. Pricing is shaped around the actual system design.", icon: "sun" },
  { title: "Solar financing", text: "Spread cost over time. Approval, rates and total borrowing cost depend on the lender and agreement.", icon: "power" },
  { title: "Property-based financing", text: "Available only through participating municipal programs, with property-tax repayment and intake limits.", icon: "home" },
  { title: "Commercial project financing", text: "Structured around project size, ownership and business requirements, with individual review required.", icon: "building" },
] as const;

const checklist = ["Municipality", "Property classification", "Ownership", "Applicant or business tax status", "Electricity consumption", "Utility service area", "Roof or land suitability", "Project start date", "Program intake status", "Required approvals", "Tax and lender eligibility"];
const steps = ["Review Your Electricity Usage", "Confirm Property and Program Eligibility", "Prepare a Custom Solar and Savings Proposal", "Explain Financing and Application Next Steps"];

function External({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="button button-secondary" href={href} target="_blank" rel="noopener noreferrer">{children}<Icon name="arrow" /></a>;
}

export function SolarIncentivesPage() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: solarIncentivesFaqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const pageSchema = { "@context": "https://schema.org", "@type": "WebPage", name: "Solar Incentives and Financing in Alberta", description: "Explore current Alberta solar incentives, Calgary CEIP financing, micro-generation credits and business tax options for homes, businesses and farms.", url: `${site.url}/solar-incentives-financing/`, dateModified: "2026-07-22" };

  return <>
    <section className="incentives-hero">
      <Image src="/media/installations/ground-mount.webp" alt="Ground-mounted solar panels in an Alberta landscape" fill priority sizes="100vw" />
      <div className="incentives-hero-rays" aria-hidden="true" />
      <div className="container incentives-hero-inner"><p className="service-label">Sun Direct Renewable · Alberta</p><h1>Solar Incentives and Financing in Alberta</h1><p>Explore current solar financing, micro-generation credits, municipal programs and business tax incentives available to qualifying Alberta properties.</p><div className="incentives-hero-actions"><CTA href="/free-solar-assessment">Get Your Solar Assessment</CTA><CTA href="#overview" secondary>Explore Current Options</CTA></div><p className="reviewed-label"><Icon name="files" />Last reviewed: {solarIncentivesData.lastReviewed}</p></div>
    </section>
    <BreadcrumbSchema current="Solar Incentives and Financing in Alberta" path="/solar-incentives-financing/" /><Breadcrumbs current="Solar Incentives and Financing in Alberta" />

    <nav className="incentives-toc" aria-label="On this page"><div className="container"><span>On this page</span><div><a href="#calgary-residential">Calgary CEIP</a><a href="#micro-generation">Micro-generation</a><a href="#business-tax">Business tax</a><a href="#ways-to-pay">Ways to pay</a><a href="#faq">FAQ</a></div></div></nav>

    <section className="section incentives-overview" id="overview"><div className="container"><div className="incentives-heading"><p className="kicker">Start with the right category</p><h2>Current options deserve a careful review.</h2><p>Programs, credits and financing are different tools. Start with your property, applicant type and electricity use—then confirm the official rules that apply.</p></div><div className="incentives-overview-grid">{overview.map(item => <a href={item.href} key={item.title}><span><Icon name={item.icon} /></span><h3>{item.title}</h3><p>{item.text}</p><b>Explore <Icon name="arrow" /></b></a>)}</div><aside className="incentives-notice"><Icon name="shield" /><p>Alberta does not currently offer a universal provincial residential solar rebate. Available financing, tax incentives and municipal programs depend on the applicant, property, municipality and project.</p></aside></div></section>

    <section className="section incentives-ceip" id="calgary-residential"><div className="container incentives-ceip-grid"><div className="incentives-ceip-copy"><p className="kicker">Calgary residential CEIP</p><h2>Property-based financing for eligible Calgary homes.</h2><p>Calgary’s Residential Clean Energy Improvement Program is financing—not a rebate. It can help approved homeowners fund eligible clean-energy improvements through their property tax bill.</p><div className="incentives-status"><span className="status-dot" /><div><strong>{solarIncentivesData.residentialCeip.status}</strong><p>{solarIncentivesData.residentialCeip.statusDetail}</p></div></div><ul className="incentives-list"><li><Icon name="check" />May finance up to 100% of eligible project costs, to $50,000</li><li><Icon name="check" />Repayment is made through the property tax bill and can extend up to 20 years</li><li><Icon name="check" />Financing remains attached to the property, subject to the agreement</li><li><Icon name="check" />Approval and program agreements are required before work starts</li></ul><div className="incentives-actions"><CTA href="/free-solar-assessment">Check Your Solar Eligibility</CTA><External href={solarIncentivesData.sources.residentialCeip}>View Official Program Information</External></div></div><aside className="incentives-source-card"><span><Icon name="home" /></span><h3>Before you plan around CEIP</h3><p>Confirm property type, tax standing, mortgage and insurance requirements, contractor requirements and the current application intake directly with the program.</p><a href={solarIncentivesData.sources.ceip} target="_blank" rel="noopener noreferrer">Alberta Municipalities CEIP <Icon name="arrow" /></a></aside></div></section>

    <section className="section incentives-commercial"><div className="container incentives-commercial-grid"><div className="incentives-commercial-image"><Image src="/media/installations/metal-roof-installation.webp" alt="Commercial rooftop solar installation" fill sizes="(max-width: 900px) 100vw, 48vw" /></div><div><p className="kicker">Calgary commercial CEIP</p><h2>Commercial financing needs a property-by-property review.</h2><p>Eligible Calgary commercial properties may be able to finance renewable-energy improvements through CEIP. It is a program for approved commercial retrofits, not a universal business incentive.</p><div className="incentives-status compact"><span className="status-dot" /><div><strong>{solarIncentivesData.commercialCeip.status}</strong><p>{solarIncentivesData.commercialCeip.statusDetail}</p></div></div><ul className="incentives-list"><li><Icon name="check" />May finance up to 100% of eligible costs, to $1 million</li><li><Icon name="check" />Repayment is collected through the property tax bill</li><li><Icon name="check" />Projects must not begin before approval and agreements</li><li><Icon name="check" />New builds, farmland and industrial-tax-class properties may not qualify</li></ul><div className="incentives-actions"><CTA href="/free-solar-assessment">Request a Commercial Solar Assessment</CTA><External href={solarIncentivesData.sources.commercialCeip}>View Commercial CEIP</External></div></div></div></section>

    <section className="section incentives-micro" id="micro-generation"><div className="container"><div className="incentives-heading center"><p className="kicker">Alberta micro-generation credits</p><h2>Use power first. Export the excess.</h2><p>Micro-generation is small-scale electricity production designed around a property’s own electricity needs—not a commercial power-generation project.</p></div><div className="micro-flow"><div><span><Icon name="sun" /></span><strong>Solar Production</strong></div><i><Icon name="arrow" /></i><div><span><Icon name="home" /></span><strong>On-Site Use</strong></div><i><Icon name="arrow" /></i><div><span><Icon name="power" /></span><strong>Excess Export</strong></div><i><Icon name="arrow" /></i><div><span><Icon name="chart" /></span><strong>Retailer Credit</strong></div></div><div className="incentives-micro-grid"><article><h3>What a solar system can do</h3><p>Electricity used directly on-site can reduce grid consumption. Excess electricity supplied to the grid may receive retailer credits under the retailer’s terms.</p></article><article><h3>What still needs review</h3><p>Retailer rates and contracts vary. Distribution, transmission, local access and other fixed charges may remain, even when a system produces power.</p></article><article><h3>What must be approved</h3><p>Utility interconnection and micro-generation requirements apply. The wire service provider reviews the notice to become a micro-generator.</p></article></div><div className="incentives-center-action"><CTA href="/free-solar-assessment">Get a Usage-Based Solar Proposal</CTA><External href={solarIncentivesData.sources.microGeneration}>Read Official Micro-Generation Guidance</External></div></div></section>

    <section className="section incentives-tax" id="business-tax"><div className="container incentives-tax-grid"><div><p className="kicker">Federal business tax incentives</p><h2>Tax treatment should be confirmed before it is assumed.</h2><p>The federal Clean Technology Investment Tax Credit may provide a refundable tax credit for qualifying new clean-technology property. Eligible solar or storage property can depend on ownership, tax status, acquisition date and use.</p><p>It is not presented here as a residential homeowner incentive, and Sun Direct Renewable does not calculate or promise a credit amount.</p><aside><Icon name="shield" /><p>Sun Direct Renewable does not provide tax advice. Confirm eligibility and claim requirements with a qualified Canadian tax professional.</p></aside><div className="incentives-actions"><CTA href="/free-solar-assessment">Discuss a Commercial Solar Project</CTA><External href={solarIncentivesData.sources.cleanTechnologyItc}>Read CRA Guidance</External></div></div><div className="incentives-tax-panel"><span><Icon name="files" /></span><h3>Questions for a tax professional</h3><ul><li>Who owns the qualifying property?</li><li>What is the entity’s Canadian tax status?</li><li>When is the property acquired and available for use?</li><li>Does the equipment and intended use meet the current rules?</li></ul></div></div></section>

    <section className="section incentives-farm"><div className="container incentives-farm-grid"><div className="incentives-farm-image"><Image src="/media/installations/rural-rooftop.webp" alt="Rural rooftop solar array on an agricultural property" fill sizes="(max-width: 900px) 100vw, 48vw" /></div><div><p className="kicker">Farm and agricultural solar</p><h2>Farm solar starts with the way the operation uses power.</h2><p>Barns, workshops, grain operations, irrigation and cold storage each create a different load profile. Rooftop and ground-mounted opportunities need to be reviewed against service capacity, land classification, municipal requirements and working access.</p><ul className="incentives-list"><li><Icon name="check" />Micro-generation and export-focused generation have different planning paths</li><li><Icon name="check" />Larger land-based projects can require agricultural and municipal impact review</li><li><Icon name="check" />Business tax incentives may be relevant where an eligible taxable entity operates the farm</li><li><Icon name="check" />No grant, financing or tax treatment should be assumed without an individual review</li></ul><CTA href="/free-solar-assessment">Request a Farm Solar Assessment</CTA></div></div></section>

    <section className="section incentives-payments" id="ways-to-pay"><div className="container"><div className="incentives-heading center"><p className="kicker">Ways to pay for solar</p><h2>Compare the path, not just the monthly number.</h2><p>Every option should be reviewed around ownership, total cost, program availability and your property’s project scope.</p></div><div className="incentives-payment-grid">{paymentOptions.map(option => <article key={option.title}><span><Icon name={option.icon} /></span><h3>{option.title}</h3><p>{option.text}</p></article>)}</div></div></section>

    <section className="section incentives-checklist"><div className="container incentives-checklist-grid"><div><p className="kicker">Incentive eligibility checklist</p><h2>What should be reviewed before you rely on an option.</h2><p>Program fit is a set of connected checks—not a single yes or no. We can help organize project information, then point you to the appropriate program, utility, lender or tax professional.</p><CTA href="/free-solar-assessment">Check My Property</CTA></div><ul>{checklist.map(item => <li key={item}><Icon name="check" />{item}</li>)}</ul></div></section>

    <section className="section incentives-process"><div className="container"><div className="incentives-heading center"><p className="kicker">Our assessment process</p><h2>A clear way to move from questions to a project plan.</h2><p>Sun Direct Renewable can help organize project information, but cannot guarantee approval, funding or tax eligibility.</p></div><ol>{steps.map((step, index) => <li key={step}><span>0{index + 1}</span><h3>{step}</h3></li>)}</ol></div></section>

    <section className="section faq-section incentives-faq" id="faq"><div className="container"><div className="incentives-heading center"><p className="kicker">Frequently asked questions</p><h2>Current answers for Alberta solar planning.</h2></div><FAQList items={[...solarIncentivesFaqs]} initiallyOpen={false} /></div></section>

    <section className="incentives-final"><div className="incentives-final-rays" aria-hidden="true" /><div className="container"><div><p className="kicker light">Your next step</p><h2>Find the Best Solar Path for Your Property</h2><p>Share your electricity usage, property type and location. We’ll review your solar potential and help identify the financing or incentive categories worth exploring.</p></div><div className="incentives-actions"><CTA href="/free-solar-assessment">Get Your Solar Assessment</CTA><CTA href="/contact" secondary>Talk to Our Team</CTA></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
  </>;
}
